# Generated by Django 5.2.3 on 2025-08-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpcart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='numberreviews',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
