# Generated by Django 5.2.3 on 2025-08-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpcart', '0002_product_numberreviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productdetail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
